### ISSUE TITLE
Missing tinkerpop-2.0.0-jar-with-dependencies.jar

### ISSUE THREAD

**Issue by DavidAnDavis2021** [gchq/gaffer-docker#325]
Went into `docker/gremlin-gaffer` on the develop branch and ran `docker compose up` and got error 
```
 => ERROR [builder 4/4] RUN ALLFILESDOWNLOADED="TRUE" &&  if [ ! -f "./tinkerpop-2.0.0-jar-with-dependencies.jar" ] && [ "${allFilesDownloaded}" = "TRUE" ]; then   wget -nv "https://  17.3s
------   
...
#0 0.332 https://repo1.maven.org/maven2/uk/gov/gchq/gaffer/tinkerpop/2.0.0/tinkerpop-2.0.0-jar-with-dependencies.jar:
#0 0.332 2023-09-01 16:47:57 ERROR 404: Not Found.
```

Looking at `https://repo1.maven.org/maven2/uk/gov/gchq/gaffer` there is no tinkerpop directory.

**Comment by GCHQDeveloper314** [comment]
This has happened because the last release of Gaffer did not contain tinkerpop. It exists only on the develop branch and hasn't had a release yet.

Our Dockerfiles attempt to handle the case where Maven Central doesn't have the released JAR by building locally.

Unfortunately, this also requires a tagged release in the repo:
https://github.com/gchq/gaffer-docker/blob/f13bb50e56e6faa236688bea4bf6401f2966eeb2/docker/gaffer/Dockerfile#L49

Until we release tinkerpop, this will be broken. You can work around this by building the JARs locally, placing them into the `files` directory and renaming them or editing the dockerfile so they're used:
https://github.com/gchq/gaffer-docker/blob/f13bb50e56e6faa236688bea4bf6401f2966eeb2/docker/gremlin-gaffer/Dockerfile#L30-L34

This also highlights a need for dockerfiles to support building directly from develop branch of Gaffer as well as tagged versions. Though this should be a separate ticket.

**Comment by GCHQDeveloper314** [comment]
JARs for tinkerpop are now available at https://repo1.maven.org/maven2/uk/gov/gchq/gaffer/tinkerpop/.

I've raised #356 to cover better building from the develop branch.
