### ISSUE TITLE
Add some documentation around the various passwords and user setup

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-docker#84]
When users get hold of the Gaffer Helm chart, the first thing they do is try and deploy it. It breaks. Why? Because they haven't setup the users and passwords for Accumulo. This can be quite confusing and it would be handy to have just a line or two saying what they need to do to fix it.

**Comment by ctas582** [comment]
You do get an error message telling you which properties need setting to provide the passwords, but maybe it's not the friendliest of messages.

I did consider adding a 'flag' to auto-generate all the passwords and secrets to make it easier for new users to just get something deployed and working. I didn't get round to it though. Partly because I think that it might be difficult to stop Helm from re-generating the passwords every time it generates the templates. So if you did a `helm upgrade` then new passwords would get generated and you would end up with a broken deployment.

**Comment by d47853** [comment]
Yeah you're right. It's been a common complaint of new users. I think it just needs a comment of what values need to be set. Maybe point them at the values-insecure.yaml to show an example and how to get it working.
