### ISSUE TITLE
Update JDK references to use Java 11

### ISSUE THREAD

**Issue by t11947** [gchq/gaffer-docker#91]
As a part of the expected Java upgrade in Gaffer, the JDK references will need updating to use JDK 11 based images.

Related: https://github.com/gchq/gaffer/issues/2300

**Comment by t92549** [comment]
Now that Java 11 isn't required for Gaffer 2, and we have refactored gaffer-docker to allow using either Accumulo 1 (requires Java 8) or Accumulo 2, I think it would be a lot of work to enable Accumulo 2 and Java 11. It would require a big restructure by splitting Accumulo 1 and 2 into different Dockerfiles, something we wanted to avoid.
Because of this, and the current limited advantages gained by using Java 11, I am closing the issue as won't do.
